Minichallenge4
sofisa16/react-certification-2020 pull request #4
Opened 2021-04-22 16:18 UTC by sofisa16

2021-04-27 04:41 UTC, MartinMolinero requested changes
I can see that in some of your components you follow the correct testing alternative (checking objects are rendered depending on props/actions on the UI) but on others you just compare against the snapshot. I would suggest that you follow the first alternative, so you can catch any errors/bugs in advance. Regarding your project, I haven't been able to see it working locally or on netlify.

2021-04-27 04:41 UTC, MartinMolinero commented on src/__tests__/components/CardWithFav/CardWithFav.test.tsx
> +  expect(tree).toMatchSnapshot();
Better test components based on actual jsx that you verify that they are present instead of verifying vs a snapshot. Check that certain elements exist, that they contain certain text, classNames, etc.

2021-04-27 04:41 UTC, MartinMolinero commented on src/__tests__/components/DetailsView/DetailsView.test.tsx
> +  expect(tree).toMatchSnapshot();
Same as comment above, which components would you expect to see given the route, and items that you are passing into the components.

2021-04-27 04:41 UTC, MartinMolinero commented on src/__tests__/components/FavoriteButton/FavoriteButton.test.tsx
> +  expect(tree).toMatchSnapshot();
Same as comment above, I would recommend you to test the clicking behavior of the button, what would you expect in terms of the sole component to happen after triggering a click

2021-04-27 04:41 UTC, MartinMolinero commented on src/__tests__/components/FavoriteView/FavoriteView.test.tsx
> +  expect(tree).toMatchSnapshot();
Same as above, you can test how many items do you expect to visualize in the favorites view, etc.

2021-04-27 04:41 UTC, MartinMolinero commented on src/__tests__/components/FavoritesDetailsView/FavoritesDetailsView.test.tsx
> +  expect(tree).toMatchSnapshot();
Same as above, test against components, not against snapshots.

2021-04-27 04:41 UTC, MartinMolinero commented on src/__tests__/components/Header/Header.test.tsx
> +  test('renders Header component', () => {
I think this test may not be necessary since you are covering this scenario on the test cases above, you need to render the component in order to fire events on buttons, etc. I would suggest to remove it and follow the pattern you followed in the ones contained inside this file in order to test the other components.

2021-04-27 04:41 UTC, MartinMolinero commented on src/__tests__/components/Header/components/SearchBox/SearchBox.test.js
> +describe('Searchbar component', () => {
Exactly, super nice testing scenarios.

2021-04-27 04:41 UTC, MartinMolinero commented on src/__tests__/components/Header/components/SearchBox/SearchBox.test.tsx
> +  it('renders SearchBox component', () => {
This test is not needed, better add expect statements in the previous one for you to verified it was rendered correctly.

2021-04-27 04:41 UTC, MartinMolinero commented on src/__tests__/utils/storage.test.ts
> +describe('localstorage tests', () => {
Super good test cases.

2021-04-27 04:41 UTC, MartinMolinero commented on src/components/Header/Header.tsx
> +  }
This can also be tested, I would suggest you to do it.

2021-04-27 04:41 UTC, MartinMolinero commented on src/components/Login/Login.tsx
> +  };
Try to test the result these functions have in your component instead of just comparing the snapshots

2021-04-28 05:28 UTC, sofisa16 commented
> I can see that in some of your components you follow the correct testing alternative (checking objects are rendered depending on props/actions on the UI) but on others you just compare against the snapshot. I would suggest that you follow the first alternative, so you can catch any errors/bugs in advance. Regarding your project, I haven't been able to see it working locally or on netlify.

Hello! This is my netlify https://sofisa16.netlify.app/ sometimes it is broken because of my app key, but it is working now. Sorry about that.

2021-05-03 05:33 UTC, MartinMolinero approved these changes
Congrats for completing your project! It was a nice one!
Overall advice that I would give you for future projects is to create meaningful tests for your components 👍

2021-05-03 05:33 UTC, MartinMolinero commented on src/__tests__/components/Header/components/SearchBox/SearchBox.test.tsx
>  });
A test regarding checking content after typing would be really good.

2021-05-03 05:33 UTC, MartinMolinero commented on src/__tests__/components/Login/Login.test.tsx
> +  it('renders Login component', () => {
Also the writing in fields behaviour could have been tested.

2021-05-03 05:33 UTC, MartinMolinero commented on src/__tests__/components/Mosaic/Mosaic.test.tsx
> +    expect(tree.getByText('Video Tour | Welcome to Wizeline Guadalajara')).toBeInTheDocument();
You could have also tested the amount of video elements that are being rendered based in home_videos.

2022-05-24 18:36 UTC, merged